// GENERATED by @edgedb/generate v0.4.1

import * as $ from "../reflection";
import * as _ from "../imports";
import _module__auth from "./ext/auth";
import _module__pgcrypto from "./ext/pgcrypto";


type __defaultExports = {
  "auth": typeof _module__auth;
  "pgcrypto": typeof _module__pgcrypto
};
const __defaultExports: __defaultExports = {
  "auth": _module__auth,
  "pgcrypto": _module__pgcrypto
};
export default __defaultExports;
