const fs = require("node:fs/promises");
const { createClient } = require("gel");

const client = createClient("_localdev");

(async function () {
  const providerNames = await client.queryRequiredSingle(`
  with
    oauth_providers := (
      select schema::ObjectType
      filter .bases.name = 'ext::auth::OAuthProviderConfig'
    ),
    emailpassword_provider := (
      select schema::ObjectType
      filter .name = 'ext::auth::EmailPasswordProviderConfig'
    )
  select {
    oauth := (
      select oauth_providers.properties filter .name = 'name'
    ).default,
    emailpassword := assert_single((
      select emailpassword_provider.properties filter .name = 'name'
    ).default)
  }`);

  await fs.writeFile(
    "./src/consts.ts",
    `// AUTOGENERATED - Run \`yarn gen-consts\` to re-generate.

export const builtinOAuthProviderNames = [
${providerNames.oauth
  .sort()
  .map((provider) => `  ${provider.replace(/^'|'$/g, '"')},`)
  .join("\n")}
] as const;
export type BuiltinOAuthProviderNames =
  (typeof builtinOAuthProviderNames)[number];

export const emailPasswordProviderName = ${providerNames.emailpassword.replace(
      /^'|'$/g,
      '"',
    )};
`,
  );

  console.log('Generated into "src/consts.ts"');
})();
