// AUTOGENERATED - Run `yarn gen-consts` to re-generate.

export const builtinOAuthProviderNames = [
  "builtin::oauth_apple",
  "builtin::oauth_azure",
  "builtin::oauth_github",
  "builtin::oauth_google",
] as const;
export type BuiltinOAuthProviderNames =
  (typeof builtinOAuthProviderNames)[number];

export const emailPasswordProviderName = "builtin::local_emailpassword";
