import type { FetchFunction } from "@ai-sdk/provider-utils";

export type OpenAIModelId =
  | "gpt-4o"
  | "gpt-4o-mini"
  | "gpt-4-turbo-preview"
  | "gpt-4-turbo"
  | "gpt-3.5-turbo"
  | "gpt-4";

export type MistralModelId =
  | "ministral-8b-latest"
  | "ministral-3b-latest"
  | "mistral-small-latest"
  | "mistral-medium-latest" // will be deprecated "soon"
  | "mistral-large-latest"
  | "codestral-latest"
  | "pixtral-12b-2409" // free model
  | "open-mistral-nemo" // free model
  | "open-codestral-mamba"; // free model

export type AnthropicModelId =
  | "claude-3-5-sonnet-20240620"
  | "claude-3-haiku-20240307"
  | "claude-3-sonnet-20240229"
  | "claude-3-opus-20240229";

export type EdgeDBRagModelId =
  | OpenAIModelId
  | MistralModelId
  | AnthropicModelId
  | (string & {});

export function isAnthropicModel(model: EdgeDBRagModelId): boolean {
  return (
    model === "claude-3-5-sonnet-20240620" ||
    model === "claude-3-haiku-20240307" ||
    model === "claude-3-sonnet-20240229" ||
    model === "claude-3-opus-20240229"
  );
}

export function isOpenAIModel(model: EdgeDBRagModelId): boolean {
  return (
    model === "gpt-4o" ||
    model === "gpt-4o-mini" ||
    model === "gpt-4-turbo-preview" ||
    model === "gpt-4-turbo" ||
    model === "gpt-3.5-turbo" ||
    model === "gpt-4"
  );
}

export type Prompt =
  | { name: string; custom?: EdgeDBRagMessage[] }
  | { id: string; custom?: EdgeDBRagMessage[] }
  | { custom: EdgeDBRagMessage[] };

export interface QueryContext {
  query: string;
  variables?: Record<string, unknown>;
  globals?: Record<string, unknown>;
  max_object_count?: number;
}

export interface EdgeDBRagConfig {
  provider: string;
  fetch: FetchFunction;
}

export interface EdgeDBRagSettings {
  context?: QueryContext;
  prompt?: Prompt;

  // Mistral only:

  /**
Whether to inject a safety prompt before all conversations.
Defaults to `false`.
   */
  safePrompt?: boolean;

  // OpenAI only

  /**
Echo back the prompt in addition to the completion.
   */
  echo?: boolean;

  /**
Modify the likelihood of specified tokens appearing in the completion.

Accepts a JSON object that maps tokens (specified by their token ID in
the GPT tokenizer) to an associated bias value from -100 to 100. You
can use this tokenizer tool to convert text to token IDs. Mathematically,
the bias is added to the logits generated by the model prior to sampling.
The exact effect will vary per model, but values between -1 and 1 should
decrease or increase likelihood of selection; values like -100 or 100
should result in a ban or exclusive selection of the relevant token.

As an example, you can pass {"50256": -100} to prevent the <|endoftext|>
token from being generated.
   */
  logitBias?: Record<number, number>;

  /** 
Return the log probabilities of the tokens. Including logprobs will increase
the response size and can slow down response times. However, it can
be useful to better understand how the model is behaving.

Setting to true will return the log probabilities of the tokens that
were generated.

Setting to a number will return the log probabilities of the top n
tokens that were generated.
   */
  logprobs?: boolean | number;

  /** 
A unique identifier representing your end-user, which can help OpenAI to
monitor and detect abuse. Learn more.
   */
  user?: string;

  // Anthropic only:

  // Enable Anthropic cache control (beta feature). This will add the beta header and
  // allow you to use provider-specific cacheControl metadata.
  // cacheControl?: boolean;
}

export type EdgeDBRagMessage =
  | EdgeDBSystemMessage
  | EdgeDBUserMessage
  | EdgeDBAssistantMessage
  | EdgeDBToolMessage;

export interface EdgeDBSystemMessage {
  role: "system";
  content: string;
}

export interface EdgeDBUserMessage {
  role: "user";
  content: { type: "text"; text: string }[];
}

export interface EdgeDBAssistantMessage {
  role: "assistant";
  content: string;
  tool_calls?: {
    id: string;
    type: "function";
    function: { name: string; arguments: string };
  }[];
}

export interface EdgeDBToolMessage {
  role: "tool";
  // name: string;
  content: string;
  tool_call_id: string;
}

// const msgs = [
//   {
//     role: "system",
//     content:
//       "You are an expert Q&A system.\nAlways answer questions based on the provided context information.\nContext information is below:\nNightshade’s Promise: A forbidden forest filled with nightshade flowers promises eternal youth, but at a price that could be too perilous.\nWhispers of the Forgotten City: Written by Elena Marquez: In the sprawling, labyrinthine city of Velloria, ancient secrets lie buried beneath cobblestone streets and candle-lit alleyways. Ivy Donovan, a young historian, stumbles upon a cryptic map that hints at the location of the legendary Sunken Library, believed to house texts lost since the city's mysterious decline centuries ago. As Ivy delves deeper into the city’s dark past, she must dodge shadowy figures who seek to keep the library's secrets hidden. Alongside an unlikely band of allies, Ivy's quest leads her through hidden passages, haunted catacombs, and forgotten ruins, where she discovers truths that could shake the foundations of her world. As they inch closer to uncovering the city's ancient mysteries, they realize some secrets might have been better left untouched.\nBeneath the Drifts: A chilling expedition beneath the ice where darkness unveils not just secrets, but a dormant, sinister will.\nWhispering Flames: Written by Seraphine Bright: In a realm where fire speaks and the ashes tell tales, a young fire whisperer must save her people from an eternal blaze.\nThe Last Alchemist: In a world drained of magic, the last alchemist undertakes a quest to reignite the lost sparks of enchantment.\nWhispers of the Forgotten: An enchanting tale of a hidden village that exists between the folds of time, where the forgotten are remembered.\nThe Gilded Mirror: A cursed mirror reflects alternative realities, trapping its viewers in a labyrinth of their potential lives.\nThe Clockmaker’s Paradox: A clockmaker in a steampunk city discovers a time paradox that could unravel the very fabric of existence.\nAshes of the Starry Sea: Written by Orion Ember: After the stars in the sky mysteriously vanish, a band of astronomers embark on a perilous journey to retrieve them.\nEchoes of the Void: A cosmic adventure across starlit galaxies to uncover the mysteries of a universe humming with the echo of ancient civilizations.\nThe Maze of Many: Written by Ariadne Thread: A labyrinth with doors leading to infinite worlds becomes a battleground for those seeking ultimate power.",
//   },
//   { role: "user", content: "where is Orion Ember from?" },
// ];

// const tools = [
//   {
//     type: "function",
//     function: {
//       name: "country",
//       description: "Get the country of the author",
//       parameters: {
//         type: "object",
//         properties: {
//           author: {
//             type: "string",
//             description: "Author name to get the country for",
//           },
//         },
//         required: ["author"],
//         additionalProperties: False,
//         $schema: "http://json-schema.org/draft-07/schema#",
//       },
//     },
//   },
// ];
