// GENERATED by @edgedb/generate v0.0.7
// Run 'npx @edgedb/generate queries' to re-generate

import type {Executor} from "edgedb";

export async function freeShape(client: Executor, args: {
  "data": string;
}): Promise<{
  "name": string;
  "points": bigint;
  "data": string;
  "arg": [(string), ...(string)[]];
  "enums": ("Horror" | "Action" | "RomCom" | "Science Fiction")[];
}> {
  return client.queryRequiredSingle(`select {
  name := "arg",
  points := 1234n,
  data := <str>$data,
  required multi arg := {'asdf'},
  enums := [Genre.Horror, Genre.Action]
};`, args);
}